const shadersToInclude = [
    // 'alphamap_fragment',
    // 'alphamap_pars_fragment',
    // 'alphatest_fragment',
    // 'alphatest_pars_fragment',
    // 'aomap_fragment',
    // 'aomap_pars_fragment',
    'begin_vertex',
    'beginnormal_vertex',
    'bsdfs',
    // 'bumpmap_pars_fragment',
    // 'clipping_planes_fragment',
    // 'clipping_planes_pars_fragment',
    // 'clipping_planes_pars_vertex',
    // 'clipping_planes_vertex',
    // 'color_fragment',
    // 'color_pars_fragment',
    // 'color_pars_vertex',
    // 'color_vertex',
    'common',
    // 'cube_uv_reflection_fragment',
    'defaultnormal_vertex',
    'displacementmap_pars_vertex',
    'displacementmap_vertex',
    'emissivemap_fragment',
    'emissivemap_pars_fragment',
    'encodings_fragment',
    'encodings_pars_fragment',
    // 'envmap_fragment',
    // 'envmap_common_pars_fragment',
    // 'envmap_pars_fragment',
    // 'envmap_pars_vertex',
    // 'envmap_vertex',
    // 'fog_vertex',
    // 'fog_pars_vertex',
    // 'fog_fragment',
    // 'fog_pars_fragment',
    // 'gradientmap_pars_fragment',
    'lightmap_fragment',
    'lightmap_pars_fragment',
    // 'lights_lambert_vertex',
    'lights_pars_begin',
    // 'envmap_physical_pars_fragment',
    // 'lights_toon_fragment',
    // 'lights_toon_pars_fragment',
    // 'lights_phong_fragment',
    // 'lights_phong_pars_fragment',
    'lights_physical_fragment',
    'lights_physical_pars_fragment',
    'lights_fragment_begin',
    'lights_fragment_maps',
    'lights_fragment_end',
    // 'logdepthbuf_fragment',
    // 'logdepthbuf_pars_fragment',
    // 'logdepthbuf_pars_vertex',
    // 'logdepthbuf_vertex',
    // 'map_fragment',
    // 'map_pars_fragment',
    // 'map_particle_fragment',
    // 'map_particle_pars_fragment',
    'metalnessmap_fragment',
    'metalnessmap_pars_fragment',
    // 'morphnormal_vertex',
    // 'morphtarget_pars_vertex',
    // 'morphtarget_vertex',
    'normal_fragment_begin',
    'normal_fragment_maps',
    'normal_pars_fragment',
    'normal_pars_vertex',
    'normal_vertex',
    'normalmap_pars_fragment',
    'clearcoat_normal_fragment_begin',
    'clearcoat_normal_fragment_maps',
    'clearcoat_pars_fragment',
    'output_fragment',
    'packing',
    'premultiplied_alpha_fragment',
    'project_vertex',
    // 'dithering_fragment',
    // 'dithering_pars_fragment',
    'roughnessmap_fragment',
    'roughnessmap_pars_fragment',
    // 'shadowmap_pars_fragment',
    // 'shadowmap_pars_vertex',
    // 'shadowmap_vertex',
    // 'shadowmask_pars_fragment',
    // 'skinbase_vertex',
    // 'skinning_pars_vertex',
    // 'skinning_vertex',
    // 'skinnormal_vertex',
    // 'specularmap_fragment',
    // 'specularmap_pars_fragment',
    'tonemapping_fragment',
    'tonemapping_pars_fragment',
    // 'transmission_fragment',
    // 'transmission_pars_fragment',
    // 'uv_pars_fragment',
    // 'uv_pars_vertex',
    // 'uv_vertex',
    // 'uv2_pars_fragment',
    // 'uv2_pars_vertex',
    // 'uv2_vertex',
    // 'worldpos_vertex',
    // 'background_frag',
    // 'background_vert',
    // 'cube_frag',
    // 'cube_vert',
    // 'depth_frag',
    // 'depth_vert',
    // 'distanceRGBA_frag',
    // 'distanceRGBA_vert',
    // 'equirect_frag',
    // 'equirect_vert',
    // 'linedashed_frag',
    // 'linedashed_vert',
    'meshbasic_frag',
    'meshbasic_vert',
    // 'meshlambert_frag',
    // 'meshlambert_vert',
    // 'meshmatcap_frag',
    // 'meshmatcap_vert',
    'meshnormal_frag',
    'meshnormal_vert',
    // 'meshphong_frag',
    // 'meshphong_vert',
    'meshphysical_frag',
    'meshphysical_vert',
    // 'meshtoon_frag',
    // 'meshtoon_vert',
    // 'points_frag',
    // 'points_vert',
    // 'shadow_frag',
    // 'shadow_vert',
    // 'sprite_frag',
    // 'sprite_vert',
];

module.exports = shadersToInclude;
