// TODO add a loading screen for the app but make it so that google bots don't look for that page
// TODO useProgress from react drei for the loading suspense fallback

// TODO automated ? lighthouse audits

// TODO aria and semantic html names
// TODO server side rendering or something

import styles from '@/styles/components/pages/Index.module.scss';
import Head from 'next/head';
import Image from 'next/image';
import type { NextPage } from 'next';

import CrateScene from '@/components/scenes/CrateScene';

import SmartCanvas from '@/components/canvas/SmartCanvas';

import Starfield from '@/components/starfield/Starfield';

import { Vector3 } from 'three';

import Navbar from '@/components/nav/Navbar';
import { Suspense } from 'react';

import ExternalButton from '@/components/nav/ExternalButton';

import TextCycle from '@/components/text/TextCycle';

import DotsBackgroundSVG from '@/components/svg/background/DotsBackgroundSVG';
import { useCurrentRef } from '@/hooks/ref';

import FadeInText from '@/components/text/FadeInText';

import ContextCanvas from '@/components/canvas/ContextCanvas';

import HomeScene from '@/components/scenes/index/HomeScene';

import TextUnderlineSVG from '@/components/svg/text/TextUnderlineSVG';

import AboutScene from '@/components/scenes/index/AboutScene';

// TODO fix the vertical positioning of the external button text

// TODO footer with credits for the google fonts and material icons etc...

import FloatTextContentContainer from '@/components/container/FloatTextContentContainer';
import LargeArrowSVG from '@/components/svg/arrow/LargeArrowSVG';

import FooterScene from '@/components/scenes/index/FooterScene';

const FOV = 45;
const CAMERA_POS = new Vector3(0, 0, 0);

const ABOUT_SCENE_HEIGHT = 14200;
const COLLECTORS_TOP = 7800;
const CREATORS_TOP = 12400;

const Home: NextPage = () => {
    const [aboutRef, onAboutRefChange] = useCurrentRef<HTMLElement>();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Suspense fallback={null}>
                <Navbar />
            </Suspense>
            {/* TODO scroll down prompt arrow */}
            <main id="main-content">
                {/* Landing page home section */}
                <section id="home" className={styles.home}>
                    <h1>CryptoCrate</h1>
                    <TextCycle
                        defaultText="The better"
                        wordToCycle="better"
                        altWords={['better', 'fairer', 'more fun', 'innovative']}
                        period={2200}
                    >
                        <br /> NFT platform
                    </TextCycle>
                    <ExternalButton id="external-button" className={styles.button} showArrow>
                        Launch App
                    </ExternalButton>
                    <ContextCanvas camera={{ position: CAMERA_POS, fov: FOV }}>
                        <HomeScene />
                        <Starfield fov={FOV} position={[0, 0, -50]} />
                    </ContextCanvas>
                </section>
                {/* Intro about section */}
                <section ref={onAboutRefChange} className={styles['about-section']} id="about">
                    <FadeInText maxOpacity={1} fadeIn={0.7}>
                        Re-thinking NFT platforms
                        <TextUnderlineSVG width="10vw" z={2} rot={1} tX="-80vw" tY="6vw" />
                    </FadeInText>
                    <div className={styles.inset}>
                        <DotsBackgroundSVG
                            element={aboutRef}
                            radius={3.2}
                            spacing={30}
                            fadeConst={1.23}
                            fadeN={4}
                            padHeight={50}
                        />
                        <FloatTextContentContainer
                            heading="A luck-based NFT platform"
                            subheading="Randomised NFTs"
                            content={
                                <LargeArrowSVG
                                    color={'black'}
                                    width={300}
                                    type={1}
                                    style={{ transform: 'translateY(1rem)' }}
                                />
                            }
                        >
                            Instead of bidding for NFTs on CryptoCrate, you open a crate that is
                            guaranteed to give a random NFT. Simple.
                        </FloatTextContentContainer>
                        <FloatTextContentContainer
                            heading="Better for everyone"
                            subheading="Helping creators and collectors"
                            content={
                                <LargeArrowSVG
                                    color={'black'}
                                    width={300}
                                    type={2}
                                    style={{ transform: 'translateY(1rem)' }}
                                />
                            }
                            rightAlign
                        >
                            CryptoCrate helps collectors and aspiring artists - both established and
                            up-and-coming. Our platform makes it easier than ever to distribute,
                            discover, and collect NFTs.
                        </FloatTextContentContainer>
                        <FloatTextContentContainer
                            heading="It's all on Ethereum"
                            subheading="Crates are tokens"
                            content={
                                <LargeArrowSVG
                                    color={'black'}
                                    width={300}
                                    type={3}
                                    style={{
                                        transform: 'translateX(-3rem) translateY(1rem) scale(1.2)',
                                    }}
                                />
                            }
                        >
                            The crates and the NFTs in them are tokens themselves on the Ethereum
                            blockchain. You can open them, store them, or trade them with other
                            people.
                        </FloatTextContentContainer>
                    </div>
                </section>
                {/* Interactive detailed about section */}
                <AboutScene />
                {/* Dummy sections for navigation */}
                <section
                    id="collectors"
                    style={{
                        position: 'absolute',
                        top: `calc(100vh + ${aboutRef?.style.height ?? 0}px + ${COLLECTORS_TOP}px)`,
                        width: '100%',
                        height: `${CREATORS_TOP - COLLECTORS_TOP}px`,
                        visibility: 'hidden',
                        zIndex: -1,
                    }}
                />
                <section
                    id="creators"
                    style={{
                        position: 'absolute',
                        top: `calc(100vh + ${aboutRef?.style.height ?? 0}px + ${CREATORS_TOP}px)`,
                        width: '100%',
                        height: `${ABOUT_SCENE_HEIGHT - CREATORS_TOP}px`,
                        visibility: 'hidden',
                        zIndex: -1,
                    }}
                />
                {/* TODO add extra section here that won't show up on the navbar */}
                <FooterScene />
            </main>

            {/* <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer> */}
        </>
    );
};

export default Home;
